# Here you can specify default options for TinyMCE across all controllers
#
# theme:  advanced
 language:  'zh'
 theme_advanced_toolbar_location:  "top"
 theme:  'advanced'  # 皮肤
 language: 'zh'  # 中文界面
 convert_urls: false # 不转换路径，否则在插入图片或头像时，会转成相对路径，容易导致路径错乱。
 theme_advanced_toolbar_location: "top"  # 工具条在上面
 theme_advanced_toolbar_align: "left"
 theme_advanced_resizing: true  # 似乎不好使
 theme_advanced_resize_horizontal: false
 paste_auto_cleanup_on_paste: true
      # 工具条上的按钮布局
 theme_advanced_buttons1: %w{formatselect fontselect fontsizeselect forecolor backcolor bold italic underline strikethrough sub sup removeformat}
 theme_advanced_buttons2: %w{undo redo cut copy paste separator justifyleft justifycenter justifyright separator indent outdent separator bullist numlist separator link unlink image media emotions separator table separator fullscreen}
 theme_advanced_buttons3: []
      # 字体列表中显示的字体
 theme_advanced_fonts: %w{宋体=宋体;黑体=黑体;仿宋=仿宋;楷体=楷体;隶书=隶书;幼圆=幼圆;Andale Mono=andale monotimes;Arial=arialhelveticasans-serif;Arial Black=arial blackavant garde;Book Antiqua=book antiquapalatino;Comic Sans MS=comic sans mssans-serif;Courier New=courier newcourier;Georgia=georgiapalatino;Helvetica=helvetica;Impact=impactchicago;Symbol=symbol;Tahoma=tahomaarialhelveticasans-serif;Terminal=terminalmonaco;Times New Roman=times new romantimes;Trebuchet MS=trebuchet msgeneva;Verdana=verdanageneva;Webdings=webdings;Wingdings=wingdingszapf dingbats} # 字体
      # : force_br_newlines: true # 此选项强制编辑器将段落符号(P)替换成换行符(BR)。不建议用：ff下不好使，用了此选项后，输入内容的居中、清单或编号都被破坏。
 plugins: %w{contextmenu paste media emotions table fullscreen}}
